declare const styles: {
    fadeIn: string;
    fadeInUp: string;
    root: string;
    header: string;
    headerCenter: string;
    assetId: string;
    headerActions: string;
    body: string;
    details: string;
    rightPanel: string;
    card: string;
    cardTitle: string;
    fieldGrid: string;
    field: string;
    fieldLabel: string;
    fieldValue: string;
    remarks: string;
    attachItem: string;
    attachInfo: string;
    attachName: string;
    attachMeta: string;
    badge: string;
    attachActions: string;
    emptyState: string;
    attachLink: string;
    repairEntry: string;
    repairHeader: string;
    timeline: string;
    timelineItem: string;
    timelineDot: string;
    timelineContent: string;
    timelineAction: string;
    timelineMeta: string;
    timelineNote: string;
};
export default styles;
//# sourceMappingURL=AssetDetail.module.scss.d.ts.map